# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/Projects/autodane/initialoptions/choosefootprint.ui'
#
# Created: Tue Dec  1 12:09:50 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1091, 486)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.txtFootprintName = QtGui.QLineEdit(self.tab)
        self.txtFootprintName.setObjectName(_fromUtf8("txtFootprintName"))
        self.verticalLayout.addWidget(self.txtFootprintName)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cmbFootprints = QtGui.QComboBox(self.tab)
        self.cmbFootprints.setObjectName(_fromUtf8("cmbFootprints"))
        self.verticalLayout.addWidget(self.cmbFootprints)
        self.cbxDoWork = QtGui.QCheckBox(self.tab)
        self.cbxDoWork.setObjectName(_fromUtf8("cbxDoWork"))
        self.verticalLayout.addWidget(self.cbxDoWork)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cmbCategories = QtGui.QComboBox(self.tab_3)
        self.cmbCategories.setObjectName(_fromUtf8("cmbCategories"))
        self.verticalLayout_5.addWidget(self.cmbCategories)
        self.tblTasks = QtGui.QTableWidget(self.tab_3)
        self.tblTasks.setObjectName(_fromUtf8("tblTasks"))
        self.tblTasks.setColumnCount(2)
        self.tblTasks.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tblTasks)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.txtTaskName = QtGui.QLineEdit(self.tab_3)
        self.txtTaskName.setObjectName(_fromUtf8("txtTaskName"))
        self.horizontalLayout.addWidget(self.txtTaskName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txtTaskDescription = QtGui.QTextEdit(self.tab_3)
        self.txtTaskDescription.setObjectName(_fromUtf8("txtTaskDescription"))
        self.horizontalLayout_2.addWidget(self.txtTaskDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtFileName = QtGui.QLineEdit(self.tab_3)
        self.txtFileName.setObjectName(_fromUtf8("txtFileName"))
        self.horizontalLayout_3.addWidget(self.txtFileName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        self.label_7.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cbxUsesMetasploit = QtGui.QCheckBox(self.tab_3)
        self.cbxUsesMetasploit.setText(_fromUtf8(""))
        self.cbxUsesMetasploit.setObjectName(_fromUtf8("cbxUsesMetasploit"))
        self.horizontalLayout_4.addWidget(self.cbxUsesMetasploit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setMinimumSize(QtCore.QSize(110, 0))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.cbxIsRecursive = QtGui.QCheckBox(self.tab_3)
        self.cbxIsRecursive.setText(_fromUtf8(""))
        self.cbxIsRecursive.setObjectName(_fromUtf8("cbxIsRecursive"))
        self.horizontalLayout_15.addWidget(self.cbxIsRecursive)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.cbxTaskEnabled = QtGui.QCheckBox(self.tab_3)
        self.cbxTaskEnabled.setText(_fromUtf8(""))
        self.cbxTaskEnabled.setObjectName(_fromUtf8("cbxTaskEnabled"))
        self.horizontalLayout_5.addWidget(self.cbxTaskEnabled)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnCreateTask = QtGui.QPushButton(self.tab_3)
        self.btnCreateTask.setObjectName(_fromUtf8("btnCreateTask"))
        self.horizontalLayout_7.addWidget(self.btnCreateTask)
        self.btnSaveTasksChanges = QtGui.QPushButton(self.tab_3)
        self.btnSaveTasksChanges.setObjectName(_fromUtf8("btnSaveTasksChanges"))
        self.horizontalLayout_7.addWidget(self.btnSaveTasksChanges)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 3)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tblTriggers = QtGui.QTableWidget(self.tab_4)
        self.tblTriggers.setObjectName(_fromUtf8("tblTriggers"))
        self.tblTriggers.setColumnCount(3)
        self.tblTriggers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_10.addWidget(self.tblTriggers)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        self.label_9.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.txtTriggerName = QtGui.QLineEdit(self.tab_4)
        self.txtTriggerName.setObjectName(_fromUtf8("txtTriggerName"))
        self.horizontalLayout_8.addWidget(self.txtTriggerName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.txtTriggerDescription = QtGui.QTextEdit(self.tab_4)
        self.txtTriggerDescription.setObjectName(_fromUtf8("txtTriggerDescription"))
        self.horizontalLayout_9.addWidget(self.txtTriggerDescription)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cmbTriggers = QtGui.QComboBox(self.tab_5)
        self.cmbTriggers.setObjectName(_fromUtf8("cmbTriggers"))
        self.verticalLayout_6.addWidget(self.cmbTriggers)
        self.tblEvents = QtGui.QTableWidget(self.tab_5)
        self.tblEvents.setObjectName(_fromUtf8("tblEvents"))
        self.tblEvents.setColumnCount(5)
        self.tblEvents.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tblEvents)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setMinimumSize(QtCore.QSize(110, 0))
        self.label_11.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.txtEventValueMask = QtGui.QLineEdit(self.tab_5)
        self.txtEventValueMask.setObjectName(_fromUtf8("txtEventValueMask"))
        self.horizontalLayout_11.addWidget(self.txtEventValueMask)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.cbxEventEnabled = QtGui.QCheckBox(self.tab_5)
        self.cbxEventEnabled.setText(_fromUtf8(""))
        self.cbxEventEnabled.setObjectName(_fromUtf8("cbxEventEnabled"))
        self.horizontalLayout_12.addWidget(self.cbxEventEnabled)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnAddEvent = QtGui.QPushButton(self.tab_5)
        self.btnAddEvent.setObjectName(_fromUtf8("btnAddEvent"))
        self.horizontalLayout_14.addWidget(self.btnAddEvent)
        self.btnSaveEvent = QtGui.QPushButton(self.tab_5)
        self.btnSaveEvent.setObjectName(_fromUtf8("btnSaveEvent"))
        self.horizontalLayout_14.addWidget(self.btnSaveEvent)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtKnownHosts = QtGui.QTextEdit(self.tab_7)
        self.txtKnownHosts.setObjectName(_fromUtf8("txtKnownHosts"))
        self.gridLayout_7.addWidget(self.txtKnownHosts, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtKnownRanges = QtGui.QTextEdit(self.tab_8)
        self.txtKnownRanges.setObjectName(_fromUtf8("txtKnownRanges"))
        self.gridLayout_8.addWidget(self.txtKnownRanges, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.txtExclude = QtGui.QTextEdit(self.tab_9)
        self.txtExclude.setObjectName(_fromUtf8("txtExclude"))
        self.gridLayout_9.addWidget(self.txtExclude, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.btnOK = QtGui.QPushButton(Dialog)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.gridLayout.addWidget(self.btnOK, 1, 0, 1, 1)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout.addWidget(self.btnCancel, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Footprint Options", None))
        self.label.setText(_translate("Dialog", "Enter the name of the footprint", None))
        self.label_2.setText(_translate("Dialog", "Or choose one from this list", None))
        self.cbxDoWork.setText(_translate("Dialog", "Carry on with footprint", None))
        self.label_3.setText(_translate("Dialog", "(Untick this if you simply want to view previous results)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Footprint", None))
        item = self.tblTasks.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Category", None))
        item = self.tblTasks.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name", None))
        self.label_4.setText(_translate("Dialog", "Task Name", None))
        self.label_5.setText(_translate("Dialog", "Description", None))
        self.label_6.setText(_translate("Dialog", "File Name", None))
        self.label_7.setText(_translate("Dialog", "Uses Metasploit", None))
        self.label_13.setText(_translate("Dialog", "Is Recursive", None))
        self.label_8.setText(_translate("Dialog", "Enabled", None))
        self.btnCreateTask.setText(_translate("Dialog", "Create Task", None))
        self.btnSaveTasksChanges.setText(_translate("Dialog", "Save Changes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "Tasks", None))
        item = self.tblTriggers.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name", None))
        item = self.tblTriggers.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tblTriggers.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "# of events", None))
        self.label_9.setText(_translate("Dialog", "Name", None))
        self.label_10.setText(_translate("Dialog", "Description", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Trigger Descriptions", None))
        item = self.tblEvents.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Trigger", None))
        item = self.tblEvents.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value Mask", None))
        item = self.tblEvents.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Task Category", None))
        item = self.tblEvents.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Task Name", None))
        item = self.tblEvents.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Enabled", None))
        self.label_11.setText(_translate("Dialog", "Value Mask", None))
        self.label_12.setText(_translate("Dialog", "Enabled", None))
        self.btnAddEvent.setText(_translate("Dialog", "Add Event", None))
        self.btnSaveEvent.setText(_translate("Dialog", "Save Changes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Events", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Mappings", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Dialog", "Known Hosts", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Dialog", "Known Ranges", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Dialog", "Exclude List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Scope", None))
        self.btnOK.setText(_translate("Dialog", "OK", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

