# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/Projects/autoDANE/initialoptions/choosefootprint.ui'
#
# Created: Tue Feb 23 13:52:38 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1091, 572)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnOK = QtGui.QPushButton(Dialog)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.gridLayout.addWidget(self.btnOK, 1, 0, 1, 1)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout.addWidget(self.btnCancel, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.txtFootprintName = QtGui.QLineEdit(self.tab)
        self.txtFootprintName.setObjectName(_fromUtf8("txtFootprintName"))
        self.verticalLayout.addWidget(self.txtFootprintName)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cmbFootprints = QtGui.QComboBox(self.tab)
        self.cmbFootprints.setObjectName(_fromUtf8("cmbFootprints"))
        self.verticalLayout.addWidget(self.cmbFootprints)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout.addWidget(self.label_21)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.sldTestDepth = QtGui.QSlider(self.tab)
        self.sldTestDepth.setMaximum(6)
        self.sldTestDepth.setPageStep(1)
        self.sldTestDepth.setOrientation(QtCore.Qt.Horizontal)
        self.sldTestDepth.setObjectName(_fromUtf8("sldTestDepth"))
        self.verticalLayout.addWidget(self.sldTestDepth)
        self.lblDepthCategory = QtGui.QLabel(self.tab)
        self.lblDepthCategory.setObjectName(_fromUtf8("lblDepthCategory"))
        self.verticalLayout.addWidget(self.lblDepthCategory)
        self.lblDepthDescription = QtGui.QLabel(self.tab)
        self.lblDepthDescription.setObjectName(_fromUtf8("lblDepthDescription"))
        self.verticalLayout.addWidget(self.lblDepthDescription)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_10)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox = QtGui.QGroupBox(self.tab_10)
        self.groupBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tblHostEnumerationPlugins = QtGui.QTableWidget(self.groupBox)
        self.tblHostEnumerationPlugins.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblHostEnumerationPlugins.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblHostEnumerationPlugins.setObjectName(_fromUtf8("tblHostEnumerationPlugins"))
        self.tblHostEnumerationPlugins.setColumnCount(2)
        self.tblHostEnumerationPlugins.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblHostEnumerationPlugins.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblHostEnumerationPlugins.setHorizontalHeaderItem(1, item)
        self.gridLayout_12.addWidget(self.tblHostEnumerationPlugins, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.cbxRunHostEnumerationPlugin = QtGui.QCheckBox(self.groupBox_2)
        self.cbxRunHostEnumerationPlugin.setObjectName(_fromUtf8("cbxRunHostEnumerationPlugin"))
        self.gridLayout_13.addWidget(self.cbxRunHostEnumerationPlugin, 0, 0, 1, 1)
        self.lblHostEnumerationPluginDescription = QtGui.QLabel(self.groupBox_2)
        self.lblHostEnumerationPluginDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblHostEnumerationPluginDescription.setObjectName(_fromUtf8("lblHostEnumerationPluginDescription"))
        self.gridLayout_13.addWidget(self.lblHostEnumerationPluginDescription, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtKnownHosts = QtGui.QTextEdit(self.tab_7)
        self.txtKnownHosts.setObjectName(_fromUtf8("txtKnownHosts"))
        self.gridLayout_7.addWidget(self.txtKnownHosts, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_13)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.txtKnownDCs = QtGui.QTextEdit(self.tab_13)
        self.txtKnownDCs.setObjectName(_fromUtf8("txtKnownDCs"))
        self.gridLayout_16.addWidget(self.txtKnownDCs, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_13, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtKnownRanges = QtGui.QTextEdit(self.tab_8)
        self.txtKnownRanges.setObjectName(_fromUtf8("txtKnownRanges"))
        self.gridLayout_8.addWidget(self.txtKnownRanges, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.txtExclude = QtGui.QTextEdit(self.tab_9)
        self.txtExclude.setObjectName(_fromUtf8("txtExclude"))
        self.gridLayout_9.addWidget(self.txtExclude, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_14)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tblDomainCreds = QtGui.QTableWidget(self.tab_14)
        self.tblDomainCreds.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblDomainCreds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblDomainCreds.setObjectName(_fromUtf8("tblDomainCreds"))
        self.tblDomainCreds.setColumnCount(6)
        self.tblDomainCreds.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(5, item)
        self.verticalLayout_9.addWidget(self.tblDomainCreds)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.btnAddDomainCreds = QtGui.QPushButton(self.tab_14)
        self.btnAddDomainCreds.setObjectName(_fromUtf8("btnAddDomainCreds"))
        self.horizontalLayout_22.addWidget(self.btnAddDomainCreds)
        self.btnDeleteDomainCreds = QtGui.QPushButton(self.tab_14)
        self.btnDeleteDomainCreds.setObjectName(_fromUtf8("btnDeleteDomainCreds"))
        self.horizontalLayout_22.addWidget(self.btnDeleteDomainCreds)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.gridLayout_17.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_14, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_12)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        self.sedAllTasks = QtGui.QSpinBox(self.groupBox_3)
        self.sedAllTasks.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedAllTasks.setProperty("value", 3)
        self.sedAllTasks.setObjectName(_fromUtf8("sedAllTasks"))
        self.horizontalLayout_16.addWidget(self.sedAllTasks)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_17.addWidget(self.label_19)
        self.sedFootprinting = QtGui.QSpinBox(self.groupBox_4)
        self.sedFootprinting.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedFootprinting.setObjectName(_fromUtf8("sedFootprinting"))
        self.horizontalLayout_17.addWidget(self.sedFootprinting)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_18.addWidget(self.label_18)
        self.sedExploits = QtGui.QSpinBox(self.groupBox_5)
        self.sedExploits.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedExploits.setObjectName(_fromUtf8("sedExploits"))
        self.horizontalLayout_18.addWidget(self.sedExploits)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_19.addWidget(self.label_16)
        self.sedPivoting = QtGui.QSpinBox(self.groupBox_6)
        self.sedPivoting.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedPivoting.setProperty("value", 5)
        self.sedPivoting.setObjectName(_fromUtf8("sedPivoting"))
        self.horizontalLayout_19.addWidget(self.sedPivoting)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_21.addWidget(self.label_22)
        self.sedPivotingMsf = QtGui.QSpinBox(self.groupBox_8)
        self.sedPivotingMsf.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedPivotingMsf.setObjectName(_fromUtf8("sedPivotingMsf"))
        self.horizontalLayout_21.addWidget(self.sedPivotingMsf)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_12)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_20.addWidget(self.label_20)
        self.sedDomainEnumeration = QtGui.QSpinBox(self.groupBox_7)
        self.sedDomainEnumeration.setMaximumSize(QtCore.QSize(55, 16777215))
        self.sedDomainEnumeration.setObjectName(_fromUtf8("sedDomainEnumeration"))
        self.horizontalLayout_20.addWidget(self.sedDomainEnumeration)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.gridLayout_15.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_12, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_11)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab_11)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.cmbNmapTiming = QtGui.QComboBox(self.tab_11)
        self.cmbNmapTiming.setObjectName(_fromUtf8("cmbNmapTiming"))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.cmbNmapTiming.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cmbNmapTiming)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.tab_11)
        self.label_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.cmbNetworkInterface = QtGui.QComboBox(self.tab_11)
        self.cmbNetworkInterface.setObjectName(_fromUtf8("cmbNetworkInterface"))
        self.horizontalLayout_13.addWidget(self.cmbNetworkInterface)
        self.btnRefreshNetworkInterfaces = QtGui.QPushButton(self.tab_11)
        self.btnRefreshNetworkInterfaces.setMinimumSize(QtCore.QSize(0, 0))
        self.btnRefreshNetworkInterfaces.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btnRefreshNetworkInterfaces.setText(_fromUtf8(""))
        self.btnRefreshNetworkInterfaces.setObjectName(_fromUtf8("btnRefreshNetworkInterfaces"))
        self.horizontalLayout_13.addWidget(self.btnRefreshNetworkInterfaces)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.gridLayout_14.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_11, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cmbCategories = QtGui.QComboBox(self.tab_3)
        self.cmbCategories.setObjectName(_fromUtf8("cmbCategories"))
        self.verticalLayout_5.addWidget(self.cmbCategories)
        self.tblTasks = QtGui.QTableWidget(self.tab_3)
        self.tblTasks.setObjectName(_fromUtf8("tblTasks"))
        self.tblTasks.setColumnCount(2)
        self.tblTasks.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTasks.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tblTasks)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.txtTaskName = QtGui.QLineEdit(self.tab_3)
        self.txtTaskName.setObjectName(_fromUtf8("txtTaskName"))
        self.horizontalLayout.addWidget(self.txtTaskName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txtTaskDescription = QtGui.QTextEdit(self.tab_3)
        self.txtTaskDescription.setObjectName(_fromUtf8("txtTaskDescription"))
        self.horizontalLayout_2.addWidget(self.txtTaskDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.txtFileName = QtGui.QLineEdit(self.tab_3)
        self.txtFileName.setObjectName(_fromUtf8("txtFileName"))
        self.horizontalLayout_3.addWidget(self.txtFileName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        self.label_7.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cbxUsesMetasploit = QtGui.QCheckBox(self.tab_3)
        self.cbxUsesMetasploit.setText(_fromUtf8(""))
        self.cbxUsesMetasploit.setObjectName(_fromUtf8("cbxUsesMetasploit"))
        self.horizontalLayout_4.addWidget(self.cbxUsesMetasploit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setMinimumSize(QtCore.QSize(110, 0))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.cbxIsRecursive = QtGui.QCheckBox(self.tab_3)
        self.cbxIsRecursive.setText(_fromUtf8(""))
        self.cbxIsRecursive.setObjectName(_fromUtf8("cbxIsRecursive"))
        self.horizontalLayout_15.addWidget(self.cbxIsRecursive)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.cbxTaskEnabled = QtGui.QCheckBox(self.tab_3)
        self.cbxTaskEnabled.setText(_fromUtf8(""))
        self.cbxTaskEnabled.setObjectName(_fromUtf8("cbxTaskEnabled"))
        self.horizontalLayout_5.addWidget(self.cbxTaskEnabled)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnCreateTask = QtGui.QPushButton(self.tab_3)
        self.btnCreateTask.setObjectName(_fromUtf8("btnCreateTask"))
        self.horizontalLayout_7.addWidget(self.btnCreateTask)
        self.btnSaveTasksChanges = QtGui.QPushButton(self.tab_3)
        self.btnSaveTasksChanges.setObjectName(_fromUtf8("btnSaveTasksChanges"))
        self.horizontalLayout_7.addWidget(self.btnSaveTasksChanges)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 3)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tblTriggers = QtGui.QTableWidget(self.tab_4)
        self.tblTriggers.setObjectName(_fromUtf8("tblTriggers"))
        self.tblTriggers.setColumnCount(3)
        self.tblTriggers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblTriggers.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_10.addWidget(self.tblTriggers)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        self.label_9.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.txtTriggerName = QtGui.QLineEdit(self.tab_4)
        self.txtTriggerName.setObjectName(_fromUtf8("txtTriggerName"))
        self.horizontalLayout_8.addWidget(self.txtTriggerName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.txtTriggerDescription = QtGui.QTextEdit(self.tab_4)
        self.txtTriggerDescription.setObjectName(_fromUtf8("txtTriggerDescription"))
        self.horizontalLayout_9.addWidget(self.txtTriggerDescription)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cmbTriggers = QtGui.QComboBox(self.tab_5)
        self.cmbTriggers.setObjectName(_fromUtf8("cmbTriggers"))
        self.verticalLayout_6.addWidget(self.cmbTriggers)
        self.tblEvents = QtGui.QTableWidget(self.tab_5)
        self.tblEvents.setObjectName(_fromUtf8("tblEvents"))
        self.tblEvents.setColumnCount(5)
        self.tblEvents.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblEvents.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tblEvents)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setMinimumSize(QtCore.QSize(110, 0))
        self.label_11.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.txtEventValueMask = QtGui.QLineEdit(self.tab_5)
        self.txtEventValueMask.setObjectName(_fromUtf8("txtEventValueMask"))
        self.horizontalLayout_11.addWidget(self.txtEventValueMask)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.cbxEventEnabled = QtGui.QCheckBox(self.tab_5)
        self.cbxEventEnabled.setText(_fromUtf8(""))
        self.cbxEventEnabled.setObjectName(_fromUtf8("cbxEventEnabled"))
        self.horizontalLayout_12.addWidget(self.cbxEventEnabled)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnAddEvent = QtGui.QPushButton(self.tab_5)
        self.btnAddEvent.setObjectName(_fromUtf8("btnAddEvent"))
        self.horizontalLayout_14.addWidget(self.btnAddEvent)
        self.btnSaveEvent = QtGui.QPushButton(self.tab_5)
        self.btnSaveEvent.setObjectName(_fromUtf8("btnSaveEvent"))
        self.horizontalLayout_14.addWidget(self.btnSaveEvent)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 2)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.cmbNmapTiming.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Footprint Options", None))
        self.btnOK.setText(_translate("Dialog", "OK", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))
        self.label.setText(_translate("Dialog", "Enter the name of the footprint", None))
        self.label_2.setText(_translate("Dialog", "Or choose one from this list", None))
        self.label_14.setText(_translate("Dialog", "Depth of test", None))
        self.lblDepthCategory.setText(_translate("Dialog", "Do nothing", None))
        self.lblDepthDescription.setText(_translate("Dialog", "No work will be done. This option will simply show previous results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Footprint", None))
        self.groupBox.setTitle(_translate("Dialog", "Host Enumeration Plugins", None))
        item = self.tblHostEnumerationPlugins.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Plugin", None))
        item = self.tblHostEnumerationPlugins.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Run", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Details", None))
        self.cbxRunHostEnumerationPlugin.setText(_translate("Dialog", "Run", None))
        self.lblHostEnumerationPluginDescription.setText(_translate("Dialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Dialog", "Initial Input", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Dialog", "Known Hosts", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("Dialog", "Known Domain Controllers", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Dialog", "Known Ranges", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Dialog", "Host Exclude List", None))
        item = self.tblDomainCreds.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Domain", None))
        item = self.tblDomainCreds.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Username", None))
        item = self.tblDomainCreds.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Password", None))
        item = self.tblDomainCreds.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "LM Hash", None))
        item = self.tblDomainCreds.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "NTLM Hash", None))
        item = self.tblDomainCreds.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Valid", None))
        self.btnAddDomainCreds.setText(_translate("Dialog", "Add", None))
        self.btnDeleteDomainCreds.setText(_translate("Dialog", "Delete", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("Dialog", "Known Domain Creds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Scope", None))
        self.groupBox_3.setTitle(_translate("Dialog", "All tasks", None))
        self.label_17.setText(_translate("Dialog", "A single thread that can handle all tasks in the queue", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Footprinting", None))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>Thread dedicated to finding and fingerprinting hosts</p><p>This will primarily focus on portscanning and vuln scanning hosts</p></body></html>", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Vuln exploitation", None))
        self.label_18.setText(_translate("Dialog", "Thread dedicated to running metasploit commands on hosts, either by exploiting vulns, or logging in with psexec", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Network pivoting", None))
        self.label_16.setText(_translate("Dialog", "Verifies domain creds, and retries them across the footprint", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Host info-gathering", None))
        self.label_22.setText(_translate("Dialog", "Logs into each host using verified creds", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Domain enumeration", None))
        self.label_20.setText(_translate("Dialog", "Handles tasks such as listing domain users and groups, extracting domain hashes etc", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("Dialog", "Threads", None))
        self.label_3.setText(_translate("Dialog", "Nmap timing template", None))
        self.cmbNmapTiming.setItemText(0, _translate("Dialog", "paranoid", None))
        self.cmbNmapTiming.setItemText(1, _translate("Dialog", "sneaky", None))
        self.cmbNmapTiming.setItemText(2, _translate("Dialog", "polite", None))
        self.cmbNmapTiming.setItemText(3, _translate("Dialog", "normal", None))
        self.cmbNmapTiming.setItemText(4, _translate("Dialog", "aggressive", None))
        self.cmbNmapTiming.setItemText(5, _translate("Dialog", "insane", None))
        self.label_15.setText(_translate("Dialog", "Network interface", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Dialog", "Advanced Options", None))
        item = self.tblTasks.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Category", None))
        item = self.tblTasks.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name", None))
        self.label_4.setText(_translate("Dialog", "Task Name", None))
        self.label_5.setText(_translate("Dialog", "Description", None))
        self.label_6.setText(_translate("Dialog", "File Name", None))
        self.label_7.setText(_translate("Dialog", "Uses metasploit", None))
        self.label_13.setText(_translate("Dialog", "Is eventless", None))
        self.label_8.setText(_translate("Dialog", "Enabled", None))
        self.btnCreateTask.setText(_translate("Dialog", "Create Task", None))
        self.btnSaveTasksChanges.setText(_translate("Dialog", "Save Changes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "Tasks", None))
        item = self.tblTriggers.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name", None))
        item = self.tblTriggers.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description", None))
        item = self.tblTriggers.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "# of events", None))
        self.label_9.setText(_translate("Dialog", "Name", None))
        self.label_10.setText(_translate("Dialog", "Description", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Trigger Descriptions", None))
        item = self.tblEvents.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Trigger", None))
        item = self.tblEvents.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value Mask", None))
        item = self.tblEvents.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Task Category", None))
        item = self.tblEvents.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Task Name", None))
        item = self.tblEvents.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Enabled", None))
        self.label_11.setText(_translate("Dialog", "Value Mask", None))
        self.label_12.setText(_translate("Dialog", "Enabled", None))
        self.btnAddEvent.setText(_translate("Dialog", "Add Event", None))
        self.btnSaveEvent.setText(_translate("Dialog", "Save Changes", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Events", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Mappings", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

