# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/autodane/source/choosefootprint.ui'
#
# Created: Wed Sep 30 22:28:02 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(485, 335)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnOK = QtGui.QPushButton(Dialog)
        self.btnOK.setDefault(True)
        self.btnOK.setFlat(False)
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.gridLayout.addWidget(self.btnOK, 1, 0, 1, 1)
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout.addWidget(self.btnCancel, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.txtFootprintName = QtGui.QLineEdit(self.tab)
        self.txtFootprintName.setObjectName(_fromUtf8("txtFootprintName"))
        self.verticalLayout.addWidget(self.txtFootprintName)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cmbFootprints = QtGui.QComboBox(self.tab)
        self.cmbFootprints.setObjectName(_fromUtf8("cmbFootprints"))
        self.verticalLayout.addWidget(self.cmbFootprints)
        self.cbxDoWork = QtGui.QCheckBox(self.tab)
        self.cbxDoWork.setChecked(False)
        self.cbxDoWork.setObjectName(_fromUtf8("cbxDoWork"))
        self.verticalLayout.addWidget(self.cbxDoWork)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cbxAddLocalResolverHosts = QtGui.QCheckBox(self.tab_5)
        self.cbxAddLocalResolverHosts.setChecked(True)
        self.cbxAddLocalResolverHosts.setObjectName(_fromUtf8("cbxAddLocalResolverHosts"))
        self.verticalLayout_2.addWidget(self.cbxAddLocalResolverHosts)
        self.cbxDnsQuery10range = QtGui.QCheckBox(self.tab_5)
        self.cbxDnsQuery10range.setObjectName(_fromUtf8("cbxDnsQuery10range"))
        self.verticalLayout_2.addWidget(self.cbxDnsQuery10range)
        self.cbxDnsQuery172range = QtGui.QCheckBox(self.tab_5)
        self.cbxDnsQuery172range.setObjectName(_fromUtf8("cbxDnsQuery172range"))
        self.verticalLayout_2.addWidget(self.cbxDnsQuery172range)
        self.cbxDnsQuery192range = QtGui.QCheckBox(self.tab_5)
        self.cbxDnsQuery192range.setObjectName(_fromUtf8("cbxDnsQuery192range"))
        self.verticalLayout_2.addWidget(self.cbxDnsQuery192range)
        self.cbxDnsQueryKnownRanges = QtGui.QCheckBox(self.tab_5)
        self.cbxDnsQueryKnownRanges.setChecked(True)
        self.cbxDnsQueryKnownRanges.setObjectName(_fromUtf8("cbxDnsQueryKnownRanges"))
        self.verticalLayout_2.addWidget(self.cbxDnsQueryKnownRanges)
        self.cbxNetRangePortScanner = QtGui.QCheckBox(self.tab_5)
        self.cbxNetRangePortScanner.setChecked(True)
        self.cbxNetRangePortScanner.setObjectName(_fromUtf8("cbxNetRangePortScanner"))
        self.verticalLayout_2.addWidget(self.cbxNetRangePortScanner)
        self.cbxZoneTransferDomains = QtGui.QCheckBox(self.tab_5)
        self.cbxZoneTransferDomains.setChecked(True)
        self.cbxZoneTransferDomains.setObjectName(_fromUtf8("cbxZoneTransferDomains"))
        self.verticalLayout_2.addWidget(self.cbxZoneTransferDomains)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cbxDnsQueriesOnKnownHosts = QtGui.QCheckBox(self.tab_2)
        self.cbxDnsQueriesOnKnownHosts.setChecked(True)
        self.cbxDnsQueriesOnKnownHosts.setObjectName(_fromUtf8("cbxDnsQueriesOnKnownHosts"))
        self.verticalLayout_3.addWidget(self.cbxDnsQueriesOnKnownHosts)
        self.cbxHostPortScanner = QtGui.QCheckBox(self.tab_2)
        self.cbxHostPortScanner.setChecked(True)
        self.cbxHostPortScanner.setObjectName(_fromUtf8("cbxHostPortScanner"))
        self.verticalLayout_3.addWidget(self.cbxHostPortScanner)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cbxVulnScanner = QtGui.QCheckBox(self.tab_3)
        self.cbxVulnScanner.setChecked(True)
        self.cbxVulnScanner.setObjectName(_fromUtf8("cbxVulnScanner"))
        self.verticalLayout_4.addWidget(self.cbxVulnScanner)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbxStartMetasploit = QtGui.QCheckBox(self.tab_4)
        self.cbxStartMetasploit.setChecked(True)
        self.cbxStartMetasploit.setObjectName(_fromUtf8("cbxStartMetasploit"))
        self.verticalLayout_5.addWidget(self.cbxStartMetasploit)
        self.cbxExploitMs08067 = QtGui.QCheckBox(self.tab_4)
        self.cbxExploitMs08067.setChecked(True)
        self.cbxExploitMs08067.setObjectName(_fromUtf8("cbxExploitMs08067"))
        self.verticalLayout_5.addWidget(self.cbxExploitMs08067)
        self.cbxExploitWeakMsSqlCreds = QtGui.QCheckBox(self.tab_4)
        self.cbxExploitWeakMsSqlCreds.setChecked(True)
        self.cbxExploitWeakMsSqlCreds.setObjectName(_fromUtf8("cbxExploitWeakMsSqlCreds"))
        self.verticalLayout_5.addWidget(self.cbxExploitWeakMsSqlCreds)
        self.cbxExploitWeakTomcatCreds = QtGui.QCheckBox(self.tab_4)
        self.cbxExploitWeakTomcatCreds.setChecked(True)
        self.cbxExploitWeakTomcatCreds.setObjectName(_fromUtf8("cbxExploitWeakTomcatCreds"))
        self.verticalLayout_5.addWidget(self.cbxExploitWeakTomcatCreds)
        self.cbxCredPivot = QtGui.QCheckBox(self.tab_4)
        self.cbxCredPivot.setChecked(True)
        self.cbxCredPivot.setObjectName(_fromUtf8("cbxCredPivot"))
        self.verticalLayout_5.addWidget(self.cbxCredPivot)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Choose Footprint", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Type the name of the footprint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Or choose one from this list", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDoWork.setText(QtGui.QApplication.translate("Dialog", "Carry on with footprint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "(Uncheck this if you simply want to view previous results)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAddLocalResolverHosts.setText(QtGui.QApplication.translate("Dialog", "Add Local Resolver Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDnsQuery10range.setText(QtGui.QApplication.translate("Dialog", "DNS Queries across 10 Range", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDnsQuery172range.setText(QtGui.QApplication.translate("Dialog", "DNS Queries across 172 Range", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDnsQuery192range.setText(QtGui.QApplication.translate("Dialog", "DNS Queries across 192 range", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDnsQueryKnownRanges.setText(QtGui.QApplication.translate("Dialog", "DNS Queries on Known Ranges", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxNetRangePortScanner.setText(QtGui.QApplication.translate("Dialog", "Net Range Port Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxZoneTransferDomains.setText(QtGui.QApplication.translate("Dialog", "Zone Transfer Domains", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Dialog", "Host Discovery", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxDnsQueriesOnKnownHosts.setText(QtGui.QApplication.translate("Dialog", "DNS Queries on Known Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxHostPortScanner.setText(QtGui.QApplication.translate("Dialog", "Host Port Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Footprinting", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxVulnScanner.setText(QtGui.QApplication.translate("Dialog", "Vuln Scanner", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Vuln Scanning", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxStartMetasploit.setText(QtGui.QApplication.translate("Dialog", "Start Metasploit", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxExploitMs08067.setText(QtGui.QApplication.translate("Dialog", "Exploit MS08-067", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxExploitWeakMsSqlCreds.setText(QtGui.QApplication.translate("Dialog", "Exploit Weak MS SQL creds", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxExploitWeakTomcatCreds.setText(QtGui.QApplication.translate("Dialog", "Exploit Weak Tomcat Creds", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCredPivot.setText(QtGui.QApplication.translate("Dialog", "Pivot using known creds", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Dialog", "Exploitation", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

