# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/autodane/source/mainwindow.ui'
#
# Created: Thu Oct  1 15:03:56 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(741, 477)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tvHosts = QtGui.QTreeView(self.tab)
        self.tvHosts.setSortingEnabled(True)
        self.tvHosts.setObjectName(_fromUtf8("tvHosts"))
        self.gridLayout_2.addWidget(self.tvHosts, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tvVulns = QtGui.QTreeView(self.tab_2)
        self.tvVulns.setSortingEnabled(True)
        self.tvVulns.setObjectName(_fromUtf8("tvVulns"))
        self.gridLayout_3.addWidget(self.tvVulns, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblDomainCreds = QtGui.QTableWidget(self.tab_3)
        self.tblDomainCreds.setObjectName(_fromUtf8("tblDomainCreds"))
        self.tblDomainCreds.setColumnCount(7)
        self.tblDomainCreds.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(6, item)
        self.gridLayout_4.addWidget(self.tblDomainCreds, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblSummary = QtGui.QLabel(self.tab_5)
        self.lblSummary.setObjectName(_fromUtf8("lblSummary"))
        self.gridLayout_6.addWidget(self.lblSummary, 0, 0, 1, 2)
        self.tblPortsSummary = QtGui.QTableWidget(self.tab_5)
        self.tblPortsSummary.setObjectName(_fromUtf8("tblPortsSummary"))
        self.tblPortsSummary.setColumnCount(2)
        self.tblPortsSummary.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblPortsSummary.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblPortsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.tblPortsSummary, 1, 0, 2, 1)
        self.tblVulnsSummary = QtGui.QTableWidget(self.tab_5)
        self.tblVulnsSummary.setObjectName(_fromUtf8("tblVulnsSummary"))
        self.tblVulnsSummary.setColumnCount(2)
        self.tblVulnsSummary.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblVulnsSummary.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblVulnsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.tblVulnsSummary, 1, 1, 1, 1)
        self.tblDomains = QtGui.QTableWidget(self.tab_5)
        self.tblDomains.setObjectName(_fromUtf8("tblDomains"))
        self.tblDomains.setColumnCount(1)
        self.tblDomains.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblDomains.setHorizontalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.tblDomains, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblWebServers = QtGui.QTableWidget(self.tab_6)
        self.tblWebServers.setObjectName(_fromUtf8("tblWebServers"))
        self.tblWebServers.setColumnCount(5)
        self.tblWebServers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblWebServers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblWebServers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblWebServers.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblWebServers.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblWebServers.setHorizontalHeaderItem(4, item)
        self.gridLayout_7.addWidget(self.tblWebServers, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblPendingVulnScanning = QtGui.QTableWidget(self.tab_7)
        self.tblPendingVulnScanning.setObjectName(_fromUtf8("tblPendingVulnScanning"))
        self.tblPendingVulnScanning.setColumnCount(2)
        self.tblPendingVulnScanning.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblPendingVulnScanning.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblPendingVulnScanning.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.tblPendingVulnScanning, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 1, 1, 1)
        self.tblPendingFootprinting = QtGui.QTableWidget(self.tab_7)
        self.tblPendingFootprinting.setObjectName(_fromUtf8("tblPendingFootprinting"))
        self.tblPendingFootprinting.setColumnCount(2)
        self.tblPendingFootprinting.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblPendingFootprinting.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblPendingFootprinting.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.tblPendingFootprinting, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.tblValidCreds = QtGui.QTableWidget(self.tab_4)
        self.tblValidCreds.setObjectName(_fromUtf8("tblValidCreds"))
        self.tblValidCreds.setColumnCount(5)
        self.tblValidCreds.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblValidCreds.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblValidCreds.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblValidCreds.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblValidCreds.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblValidCreds.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tblValidCreds, 1, 0, 1, 1)
        self.tblInvalidCreds = QtGui.QTableWidget(self.tab_4)
        self.tblInvalidCreds.setObjectName(_fromUtf8("tblInvalidCreds"))
        self.tblInvalidCreds.setColumnCount(5)
        self.tblInvalidCreds.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblInvalidCreds.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblInvalidCreds.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblInvalidCreds.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblInvalidCreds.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblInvalidCreds.setHorizontalHeaderItem(4, item)
        self.gridLayout_5.addWidget(self.tblInvalidCreds, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.tab_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_5 = QtGui.QLabel(self.tab_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.tab_8)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_9 = QtGui.QLabel(self.tab_8)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblEmailIcon = QtGui.QLabel(self.tab_8)
        self.lblEmailIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.lblEmailIcon.setObjectName(_fromUtf8("lblEmailIcon"))
        self.horizontalLayout.addWidget(self.lblEmailIcon)
        self.label_8 = QtGui.QLabel(self.tab_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblEmailIcon2 = QtGui.QLabel(self.tab_8)
        self.lblEmailIcon2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblEmailIcon2.setObjectName(_fromUtf8("lblEmailIcon2"))
        self.horizontalLayout_2.addWidget(self.lblEmailIcon2)
        self.label_13 = QtGui.QLabel(self.tab_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblSkypeLogo = QtGui.QLabel(self.tab_8)
        self.lblSkypeLogo.setObjectName(_fromUtf8("lblSkypeLogo"))
        self.horizontalLayout_3.addWidget(self.lblSkypeLogo)
        self.label_10 = QtGui.QLabel(self.tab_8)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab_8)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblSensePostLogo = QtGui.QLabel(self.frame)
        self.lblSensePostLogo.setMinimumSize(QtCore.QSize(300, 250))
        self.lblSensePostLogo.setObjectName(_fromUtf8("lblSensePostLogo"))
        self.gridLayout_9.addWidget(self.lblSensePostLogo, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_11 = QtGui.QLabel(self.tab_8)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 5)
        self.btnAddHost = QtGui.QPushButton(self.centralWidget)
        self.btnAddHost.setObjectName(_fromUtf8("btnAddHost"))
        self.gridLayout.addWidget(self.btnAddHost, 1, 0, 1, 1)
        self.btnAddDomain = QtGui.QPushButton(self.centralWidget)
        self.btnAddDomain.setObjectName(_fromUtf8("btnAddDomain"))
        self.gridLayout.addWidget(self.btnAddDomain, 1, 1, 1, 1)
        self.btnAddDomainCreds = QtGui.QPushButton(self.centralWidget)
        self.btnAddDomainCreds.setObjectName(_fromUtf8("btnAddDomainCreds"))
        self.gridLayout.addWidget(self.btnAddDomainCreds, 1, 2, 1, 1)
        self.btnUpdateUI = QtGui.QPushButton(self.centralWidget)
        self.btnUpdateUI.setObjectName(_fromUtf8("btnUpdateUI"))
        self.gridLayout.addWidget(self.btnUpdateUI, 1, 3, 1, 1)
        self.cbxUpdateUI = QtGui.QCheckBox(self.centralWidget)
        self.cbxUpdateUI.setMinimumSize(QtCore.QSize(115, 0))
        self.cbxUpdateUI.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbxUpdateUI.setChecked(True)
        self.cbxUpdateUI.setObjectName(_fromUtf8("cbxUpdateUI"))
        self.gridLayout.addWidget(self.cbxUpdateUI, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Hosts", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Vulnerabilities", None, QtGui.QApplication.UnicodeUTF8))
        self.tblDomainCreds.setSortingEnabled(True)
        item = self.tblDomainCreds.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Is DA", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "lm hash", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "ntlm hash", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblDomainCreds.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "http ntlm hash", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Domain Credentials", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSummary.setText(QtGui.QApplication.translate("MainWindow", "Identified 0 hosts, 0 open ports, 0 shells", None, QtGui.QApplication.UnicodeUTF8))
        self.tblPortsSummary.setSortingEnabled(True)
        item = self.tblPortsSummary.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblPortsSummary.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Number Found", None, QtGui.QApplication.UnicodeUTF8))
        self.tblVulnsSummary.setSortingEnabled(True)
        item = self.tblVulnsSummary.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vulnerability", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblVulnsSummary.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Number Found", None, QtGui.QApplication.UnicodeUTF8))
        self.tblDomains.setSortingEnabled(True)
        item = self.tblDomains.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.tblWebServers.setSortingEnabled(True)
        item = self.tblWebServers.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblWebServers.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblWebServers.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblWebServers.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "URL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblWebServers.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Web Servers", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblPendingVulnScanning.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Port to check", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblPendingVulnScanning.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pending Vuln Scanning", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblPendingFootprinting.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Work", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblPendingFootprinting.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pending Footprinting", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Pending Work", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Valid Creds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Invalid Creds", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblValidCreds.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblValidCreds.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblValidCreds.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblValidCreds.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblValidCreds.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblInvalidCreds.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblInvalidCreds.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblInvalidCreds.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblInvalidCreds.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblInvalidCreds.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Cred Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "autodane v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Written by Dane Goodwin,", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Security Analyst at SensePost", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmailIcon.setText(QtGui.QApplication.translate("MainWindow", "emailicon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Research@SensePost.com", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmailIcon2.setText(QtGui.QApplication.translate("MainWindow", "emailicon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Dane@SensePost.com", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSkypeLogo.setText(QtGui.QApplication.translate("MainWindow", "skypelogo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "dane_goodwin", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSensePostLogo.setText(QtGui.QApplication.translate("MainWindow", "SP Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "SensePost.com", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddHost.setText(QtGui.QApplication.translate("MainWindow", "Add Host", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDomain.setText(QtGui.QApplication.translate("MainWindow", "Add Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDomainCreds.setText(QtGui.QApplication.translate("MainWindow", "Add Domain Creds", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdateUI.setText(QtGui.QApplication.translate("MainWindow", "Update UI", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxUpdateUI.setToolTip(QtGui.QApplication.translate("MainWindow", "Update the UI every second", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxUpdateUI.setText(QtGui.QApplication.translate("MainWindow", "Continuously", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

